# Generated by Django 3.1.6 on 2021-06-03 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Miasto')),
            ],
        ),
        migrations.CreateModel(
            name='OfferPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='OfferWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Strona')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł')),
                ('address', models.CharField(max_length=255, verbose_name='Adres')),
                ('type', models.IntegerField(choices=[(1, 'Dom'), (2, 'Mieszkanie'), (3, 'Wynajem'), (4, 'Działka')], verbose_name='Rodzaj')),
                ('area', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Powierzchnia')),
                ('rooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ilość pokoi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cena')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Utworzono')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Ostatnia edycja')),
                ('link', models.URLField(verbose_name='Link')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.offercity')),
                ('photos', models.ManyToManyField(to='website.OfferPhoto', verbose_name='Zdjęcia')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.offerwebsite')),
            ],
        ),
    ]
