# Generated by Django 3.1.6 on 2021-06-03 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.offercity', verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.offerwebsite', verbose_name='Strona'),
        ),
    ]
